- markdown: "## Notice\nThanks for this contribution. We _really_ appreciate your help! :heart:"
  pathFilter:
    - '*'
- markdown: |
    ## Blocking issue
    We no longer check in binaries to this repo - our new convention is to use NuGet packages.

    Read more about this change [here](https://www.nuget.org/).
  blocking: true
  pathFilter:
    - '+**/*.dll'
- markdown: |
    ## Information
    You modified a file that controls the payment processing for the company. Please ensure that you have completed all of the following:
      - [ ] Added unit tests to verify changes
      - [ ] Tested change in multiple web browsers (Chrome, Firefox, Safari, and Edge)
      - [ ] Updated documentation with any API changes
  pathFilter:
    - '**/*.ts'
