- markdown: |
    ## Rockstar alert
    Thanks for this contribution, we _really_ appreciate your help :heart:!

- markdown: |
    Are you _sure_ you want to be console logging or debuggering here?? :trollface:
  pathFilter:
    - 'src/**'
  contentFilter:
    - '(\+\s*console.log\(.*\))'
    - '(\+\s*debugger)'

- markdown: |
    Please proofread any changes to documentation.
  pathFilter:
    - '**/*.md'

- markdown: |
    Uhh... don't check in binaries here - we use GitHub package registry for that!
  blocking: true
  pathFilter:
    - '+**/*.dll'

- markdown: |
    Testing - fail if the file doesn't include "always()"
  pathFilter:
    - '.github/workflows/example.yml'
  contentFilter:
    - '!always()'
