- markdown: |
    ## Rockstar alert
    Thanks for this contribution, we _really_ appreciate your help :heart:!
- markdown: |
    Please proofread any changes to documentation.
  pathFilter:
    - '**/*.md'
- markdown: |
    ## Uh oh
    Don't check in binaries...we use GitHub package registry for that!
  blocking: true
  pathFilter:
    - '+**/*.dll'
