name: 'Build and test nitpicker'
on:
  [push, pull_request]:
    branches:
      - master
      - 'releases/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
      - name: nitpicker
        uses: ./
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
